apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-disk
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: shared-disk
    fsType: ext4